module Phoebe
  module Models
    module Ref
      module Hotspot
        type info_retrieve_params =
          {  } & Phoebe::Internal::Type::request_parameters

        class InfoRetrieveParams < Phoebe::Internal::Type::BaseModel
          extend Phoebe::Internal::Type::RequestParameters::Converter
          include Phoebe::Internal::Type::RequestParameters

          def initialize: (?request_options: Phoebe::request_opts) -> void
        end
      end
    end
  end
end
