module Phoebe
  module Models
    module Ref
      module Hotspot
        type info_retrieve_params =
          { loc_id: String } & Phoebe::Internal::Type::request_parameters

        class InfoRetrieveParams < Phoebe::Internal::Type::BaseModel
          extend Phoebe::Internal::Type::RequestParameters::Converter
          include Phoebe::Internal::Type::RequestParameters

          attr_accessor loc_id: String

          def initialize: (
            loc_id: String,
            ?request_options: Phoebe::request_opts
          ) -> void

          def to_hash: -> {
            loc_id: String,
            request_options: Phoebe::RequestOptions
          }
        end
      end
    end
  end
end
