# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "phoebe/version"
require_relative "phoebe/internal/util"
require_relative "phoebe/internal/type/converter"
require_relative "phoebe/internal/type/unknown"
require_relative "phoebe/internal/type/boolean"
require_relative "phoebe/internal/type/file_input"
require_relative "phoebe/internal/type/enum"
require_relative "phoebe/internal/type/union"
require_relative "phoebe/internal/type/array_of"
require_relative "phoebe/internal/type/hash_of"
require_relative "phoebe/internal/type/base_model"
require_relative "phoebe/internal/type/base_page"
require_relative "phoebe/internal/type/request_parameters"
require_relative "phoebe/internal"
require_relative "phoebe/request_options"
require_relative "phoebe/file_part"
require_relative "phoebe/errors"
require_relative "phoebe/internal/transport/base_client"
require_relative "phoebe/internal/transport/pooled_net_requester"
require_relative "phoebe/client"
require_relative "phoebe/models/data/observation"
require_relative "phoebe/models/data/observations/geo/recent/notable_list_params"
require_relative "phoebe/models/data/observations/geo/recent/notable_list_response"
require_relative "phoebe/models/data/observations/geo/recent/specie_list_params"
require_relative "phoebe/models/data/observations/geo/recent/specie_list_response"
require_relative "phoebe/models/data/observations/geo/recent_list_params"
require_relative "phoebe/models/data/observations/geo/recent_list_response"
require_relative "phoebe/models/data/observations/nearest/geo_specie_list_params"
require_relative "phoebe/models/data/observations/nearest/geo_specie_list_response"
require_relative "phoebe/models/data/observations/recent/historic_list_params"
require_relative "phoebe/models/data/observations/recent/historic_list_response"
require_relative "phoebe/models/data/observations/recent/notable_list_params"
require_relative "phoebe/models/data/observations/recent/notable_list_response"
require_relative "phoebe/models/data/observations/recent/specie_retrieve_params"
require_relative "phoebe/models/data/observations/recent/specie_retrieve_response"
require_relative "phoebe/models/data/observations/recent_list_params"
require_relative "phoebe/models/data/observations/recent_list_response"
require_relative "phoebe/models/product/checklist_view_params"
require_relative "phoebe/models/product/checklist_view_response"
require_relative "phoebe/models/product/list_retrieve_params"
require_relative "phoebe/models/product/list_retrieve_response"
require_relative "phoebe/models/product/lists/historical_retrieve_params"
require_relative "phoebe/models/product/lists/historical_retrieve_response"
require_relative "phoebe/models/product/species_list_list_params"
require_relative "phoebe/models/product/species_list_list_response"
require_relative "phoebe/models/product/stat_retrieve_params"
require_relative "phoebe/models/product/stat_retrieve_response"
require_relative "phoebe/models/product/top100_retrieve_params"
require_relative "phoebe/models/product/top100_retrieve_response"
require_relative "phoebe/models/ref/hotspot/geo_retrieve_params"
require_relative "phoebe/models/ref/hotspot/geo_retrieve_response"
require_relative "phoebe/models/ref/hotspot/info_retrieve_params"
require_relative "phoebe/models/ref/hotspot/info_retrieve_response"
require_relative "phoebe/models/ref/hotspot_list_params"
require_relative "phoebe/models/ref/hotspot_list_response"
require_relative "phoebe/models/ref/region/adjacent_list_params"
require_relative "phoebe/models/ref/region/adjacent_list_response"
require_relative "phoebe/models/ref/region/info_retrieve_params"
require_relative "phoebe/models/ref/region/info_retrieve_response"
require_relative "phoebe/models/ref/region/list_list_params"
require_relative "phoebe/models/ref/region/list_list_response"
require_relative "phoebe/models/ref/taxonomy/ebird_retrieve_params"
require_relative "phoebe/models/ref/taxonomy/ebird_retrieve_response"
require_relative "phoebe/models/ref/taxonomy/form_list_params"
require_relative "phoebe/models/ref/taxonomy/form_list_response"
require_relative "phoebe/models/ref/taxonomy/locale_list_params"
require_relative "phoebe/models/ref/taxonomy/locale_list_response"
require_relative "phoebe/models/ref/taxonomy/species_group_list_params"
require_relative "phoebe/models/ref/taxonomy/species_group_list_response"
require_relative "phoebe/models/ref/taxonomy/version_list_params"
require_relative "phoebe/models/ref/taxonomy/version_list_response"
require_relative "phoebe/models"
require_relative "phoebe/resources/data"
require_relative "phoebe/resources/data/observations"
require_relative "phoebe/resources/data/observations/geo"
require_relative "phoebe/resources/data/observations/geo/recent"
require_relative "phoebe/resources/data/observations/geo/recent/notable"
require_relative "phoebe/resources/data/observations/geo/recent/species"
require_relative "phoebe/resources/data/observations/nearest"
require_relative "phoebe/resources/data/observations/nearest/geo_species"
require_relative "phoebe/resources/data/observations/recent"
require_relative "phoebe/resources/data/observations/recent/historic"
require_relative "phoebe/resources/data/observations/recent/notable"
require_relative "phoebe/resources/data/observations/recent/species"
require_relative "phoebe/resources/product"
require_relative "phoebe/resources/product/checklist"
require_relative "phoebe/resources/product/lists"
require_relative "phoebe/resources/product/lists/historical"
require_relative "phoebe/resources/product/species_list"
require_relative "phoebe/resources/product/stats"
require_relative "phoebe/resources/product/top100"
require_relative "phoebe/resources/ref"
require_relative "phoebe/resources/ref/hotspot"
require_relative "phoebe/resources/ref/hotspot/geo"
require_relative "phoebe/resources/ref/hotspot/info"
require_relative "phoebe/resources/ref/region"
require_relative "phoebe/resources/ref/region/adjacent"
require_relative "phoebe/resources/ref/region/info"
require_relative "phoebe/resources/ref/region/list"
require_relative "phoebe/resources/ref/taxonomy"
require_relative "phoebe/resources/ref/taxonomy/ebird"
require_relative "phoebe/resources/ref/taxonomy/forms"
require_relative "phoebe/resources/ref/taxonomy/locales"
require_relative "phoebe/resources/ref/taxonomy/species_groups"
require_relative "phoebe/resources/ref/taxonomy/versions"
