module Phoebe
  module Resources
    class Ref
      class Hotspot
        attr_reader geo: Phoebe::Resources::Ref::Hotspot::Geo

        attr_reader info: Phoebe::Resources::Ref::Hotspot::Info

        def list: (
          String region_code,
          ?back: Integer,
          ?fmt: Phoebe::Models::Ref::HotspotListParams::fmt,
          ?request_options: Phoebe::request_opts
        ) -> Phoebe::Models::Ref::hotspot_list_response

        def initialize: (client: Phoebe::Client) -> void
      end
    end
  end
end
