module Phoebe
  module Models
    module Product
      type checklist_view_params =
        { sub_id: String } & Phoebe::Internal::Type::request_parameters

      class ChecklistViewParams < Phoebe::Internal::Type::BaseModel
        extend Phoebe::Internal::Type::RequestParameters::Converter
        include Phoebe::Internal::Type::RequestParameters

        attr_accessor sub_id: String

        def initialize: (
          sub_id: String,
          ?request_options: Phoebe::request_opts
        ) -> void

        def to_hash: -> {
          sub_id: String,
          request_options: Phoebe::RequestOptions
        }
      end
    end
  end
end
