module Phoebe
  module Models
    module Ref
      module Region
        type adjacent_list_params =
          {  } & Phoebe::Internal::Type::request_parameters

        class AdjacentListParams < Phoebe::Internal::Type::BaseModel
          extend Phoebe::Internal::Type::RequestParameters::Converter
          include Phoebe::Internal::Type::RequestParameters

          def initialize: (?request_options: Phoebe::request_opts) -> void

          def to_hash: -> { request_options: Phoebe::RequestOptions }
        end
      end
    end
  end
end
