module Phoebe
  module Models
    module Ref
      module Region
        type adjacent_list_params =
          { region_code: String } & Phoebe::Internal::Type::request_parameters

        class AdjacentListParams < Phoebe::Internal::Type::BaseModel
          extend Phoebe::Internal::Type::RequestParameters::Converter
          include Phoebe::Internal::Type::RequestParameters

          attr_accessor region_code: String

          def initialize: (
            region_code: String,
            ?request_options: Phoebe::request_opts
          ) -> void

          def to_hash: -> {
            region_code: String,
            request_options: Phoebe::RequestOptions
          }
        end
      end
    end
  end
end
